apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: postgres-exporter
  spec:
    ports:
    - protocol: TCP
      port: 9187
    selector:
      app: postgres-exporter
- apiVersion: v1
  kind: Service
  metadata:
    name: postgres
  spec:
    ports:
    - protocol: TCP
      port: 5432
    selector:
      app: postgres
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: postgres
    labels:
      app: postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    template:
      metadata:
        labels:
          app: postgres
      spec:
        containers:
          - name: postgres
            image: postgres:9.5
            ports:
            - containerPort: 5432
            env:
            - name: POSTGRES_PASSWORD
              value: secret
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: postgres-exporter
    labels:
      app: postgres-exporter
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres-exporter
    template:
      metadata:
        labels:
          app: postgres-exporter
      spec:
        containers:
          - name: postgres-exporter
            image: wrouesnel/postgres_exporter:latest
            ports:
            - containerPort: 9187
            env:
            - name: DATA_SOURCE_NAME
              value: postgresql://postgres:secret@postgres/postgres?sslmode=disable
            - name: GODEBUG
              value: netdns=5
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: curl-looper
    labels:
      app: curl-looper
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: curl-looper
    template:
      metadata:
        labels:
          app: curl-looper
      spec:
        containers:
          - name: curl-looper
            image: jamesnetherton/curl-looper:latest
            command: [
              "/bin/sh",
              "/scrape.sh",
              "http://postgres-exporter:9187/metrics"
            ]
